apiVersion: v1
kind: Service
metadata:
  name: myapp-envoy
  labels:
    app: myapp-envoy
spec:
  type: NodePort
  #type: ClusterIP
  ports:
  - name: http
    port: 80
    nodePort: 30036
    targetPort: http
  selector:
    app: myapp-envoy
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp-envoy
  labels:
    app: myapp-envoy
spec:
  selector:
    matchLabels:
      app: myapp-envoy
  template:
    metadata:
      labels:
        app: myapp-envoy
    spec:
      containers:
      - name: myapp-envoy
        image: lubowsky/myapp-envoy:3
        imagePullPolicy: Always
        env:
        - name: "ENVOY_LB_ALG"
          value: "LEAST_REQUEST"
        - name: "SERVICE_NAME1"
          value: "myapp1"
        - name: "SERVICE_NAME2"
          value: "myapp2"
        ports:
        - name: http
          containerPort: 80
        - name: envoy-admin
          containerPort: 9901
