apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: default
  labels:
    k8s-app: fluentd-logging
data:
  fluent.conf: |
    <source>
      @type  tail
      @id    input1
      path            /var/log/containers/*.log
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      format json
      read_from_head true
      @label @mainstream
    </source>

    <match **>
      @type stdout
    </match>

    <label @mainstream>
      <match **>
        @type file
        @id   output1
        path         /fluentd/log/data.*.log
        symlink_path /fluentd/log/data.log
        append       true
        time_slice_format %Y%m%d
        time_slice_wait   10m
        time_format       %Y%m%dT%H%M%S%z
      </match>
    </label>
