kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default-user # Name is case sensitive
  namespace: default
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: exchange-deploy-role # must match the name of the Role
  apiGroup: rbac.authorization.k8s.io
