apiVersion: v1
kind: Pod
metadata:
  name: sidecar-logging
  labels:
    app: sidecar-logging
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: varlog
      mountPath: /var/log/nginx/
    ports:
    - containerPort: 80
  - name: busybox
    image: busybox
    args: [/bin/sh, -c, 'tail -f /var/log/nginx/access.log']
    volumeMounts:
    - name: varlog
      mountPath: /var/log/nginx/
  volumes:
  - name: varlog
