apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres
    nodePort: 31846
  selector:
    app: postgres
  type: NodePort
