apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    server: "192.168.42.89"
    path: "/var/nfs/general"
