kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nexus-pv-claim
  namespace: nexus
  labels:
    app: nexus
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
