apiVersion: v1
kind: Service
metadata:
  namespace: nexus
  name: nexus-nodeport
  labels:
    app: nexus
spec:
  type: NodePort
  selector:
    app: nexus
  ports:
  - name: http
    port: 8081
    nodePort: 30339
